### PR TITLE
Improve Test coverage and Remove utils

### PR DESCRIPTION
**Pull request by DanRyanIrish**
This PR increases test coverage of the package.  In doing so, it also resulted in the following changes in addition to the extra tests:
* SpectrogramCube.apply_exposure_time_correction is made independent of the number of data axes and the axis number of time axis.
* Implementation of the ```SnSSlicer``` is simplified so that is uses the ```NDCubeSequence``` slicing infrastructure.
* Because the above simplification, the entire utils directory is removed as it is no longer required.

### CODE REVIEW

**Comment by nabobalis** [comment]
Coverage seems to be working on the website but I think until the CI passes, coverage won't report on a PR.

**Comment by DanRyanIrish** [comment]
Argh!  That's a pain.  But the website is still useful.

I see that the website it updating as I update this PR.  But I see no label telling me the results are for this PR.  Is there somewhere else I should be looking?  Or does the website just show the latest build irrespective of branch or PR?

**Comment by nabobalis** [comment]
Can't say, I've never used the website in any meaningful way.

**Comment by DanRyanIrish** [comment]
OK, thanks!

**Comment by DanRyanIrish** [comment]
Hi @kakirastern.  This PR is ready to go.  Would be interested in giving it a quick review?

**Comment by kakirastern** [comment]
@DanRyanIrish Yup, sure! Let me review the PR now.

**Comment by kakirastern** [comment]
@DanRyanIrish I have checked the changes made in this PR and found no major issues with it. 

Also, I did go through the error logs for the CI tests ran previously. So for the `sunpy.sunraster (py38-32bit [linux32])` checks I see mostly the following repeated error:
```
ValueError: 2nd element of extra coordinate tuple must be None or an int giving the data axis to which the coordinate corresponds.
```

In additional I see for the `sunpy.sunraster (py38-devdeps [linux])` checks I see mainly the following repeated error:
```
AttributeError: 'SpectrogramCube' object has no attribute 'missing_axes'
```

I am aware that these are known issues to be sorted out soon.

**Comment by DanRyanIrish** [comment]
Thanks, @kakirastern!  The ```missing_axes``` is due to API breaking changes in ndcube master.  But this is not an issue on the stable release of ndcube so is not a problem at this time for sunraster.

I'm going to chase down the other error you saw just to make sure it is something similar.

**Pull request merged**
