### PR TITLE
Remove IRIS code except spectrograph reader.

### PR DESCRIPTION
**Pull request by DanRyanIrish**
This PR removes IRIS-specific code except for the IRIS spectrograph reader function.  This was placed in a new module ```io/iris.py```.  This PR also edits the reader function to return the data in generic ```sunraster``` and ```ndcube``` objects.

Addresses Issue #137 

To Do:
- [x] Make IRIS reader output generic data types: ```SpectrogramCube```, ```RasterSequence```, ```NDCollection``` (instead of ```IRISpectrograph```).

### CODE REVIEW

**Comment by kakirastern** [comment]
Looks like for the `ci/circleci: html-docs` we got stuck with the docstring bug from `ndcube`...

**Comment by kakirastern** [comment]
It looks like one change I have made to the line immediately following L407 in file `data/data_classes.rst` by adding the following didn't get picked up: 
```
['slit step' None 'spectral']
```
I know this looks a bit awkward, but without it the test on `ci/circleci: html-docs` could not get passed, at least on my laptop.

**Comment by kakirastern** [comment]
Have added this PR in case it is needed: https://github.com/DanRyanIrish/sunraster/pull/7

**Comment by DanRyanIrish** [comment]
> It looks like one change I have made to the line immediately following L407 in file `data/data_classes.rst` by adding the following didn't get picked up:
> 
> ```
> ['slit step' None 'spectral']
> ```
> 
> I know this looks a bit awkward, but without it the test on `sunpy.sunraster` could not get passed, at least on my laptop.

I deliberately didn't include this addition because the print statement that caused it has been deleted from the code.  So it is not output in the doctests anymore...or at least it shouldn't!

**Pull request merged**
