### PR TITLE
Make RasterSequence aware of instrument axis types: 2nd attempt

### PR DESCRIPTION
**Pull request by DanRyanIrish**
This PR adds awareness to RasterSequence of its instrument axis types. This is in addition to ```world_axis_physical_types``` which gives the real world coordinates of the axes. By contrast, these new axis types define the axes as ```'raster scan'```, ```'slit step'```, ```'position along slit' ```and ```'spectral'```. This information will update as the RasterSequence as it is sliced etc.

It also breaks RasterSequence out into its own module, like NDCubeSequence as the lines of code are now enough to justify that.

This PR addresses Issue #131

### CODE REVIEW

**Comment by kakirastern** [comment]
I am going to review the code in this PR shortly.

**Comment by kakirastern** [comment]
Have just repeated the tests regarding the `Raster` and `RasterSequence` contained in `sunraster/tests/test_raster.py` today. Everything checks out as expected. Will move on to try and find some edge cases and test those as well. The goal is to try and break `RasterSequence` if possible and check for robustness/vulnerability of the existing code.

**Comment by kakirastern** [comment]
Cannot help but noticed one little minor detail, however. I see the following in `sunraster/tests/test_raster.py`:
``` python
SOURCE_DATA_DN = np.array([[[ 0.563,  1.132, -1.343], [-0.719,  1.441, 1.566]],
                           [[ 0.563,  1.132, -1.343], [-0.719,  1.441, 1.566]]])
SOURCE_UNCERTAINTY_DN = np.sqrt(SOURCE_DATA_DN)
```
This would lead to a warning as follows:
``` python
/opt/anaconda3/envs/astro/bin/ipython:1: RuntimeWarning: invalid value encountered in sqrt
  #!/opt/anaconda3/envs/astro/bin/python
``` 

Should I patch this code snippet and set a mask for the quantities in `SOURCE_DATA_DN` so that everything passed into the mask will be at least zero for this to be "physical"? The square root of a negative value is some complex number and this case could be considered as "unphysical".

**Comment by kakirastern** [comment]
@DanRyanIrish Found a bug in the PR, and have opened a PR on https://github.com/DanRyanIrish/sunraster/pull/1 to follow up on my code review.

**Comment by DanRyanIrish** [comment]
> Cannot help but noticed one little minor detail, however. I see the following in `sunraster/tests/test_raster.py`:
> 
> ```python
> SOURCE_DATA_DN = np.array([[[ 0.563,  1.132, -1.343], [-0.719,  1.441, 1.566]],
>                            [[ 0.563,  1.132, -1.343], [-0.719,  1.441, 1.566]]])
> SOURCE_UNCERTAINTY_DN = np.sqrt(SOURCE_DATA_DN)
> ```
> 
> This would lead to a warning as follows:
> 
> ```python
> /opt/anaconda3/envs/astro/bin/ipython:1: RuntimeWarning: invalid value encountered in sqrt
>   #!/opt/anaconda3/envs/astro/bin/python
> ```
> 
> Should I patch this code snippet and set a mask for the quantities in `SOURCE_DATA_DN` so that everything passed into the mask will be at least zero for this to be "physical"? The square root of a negative value is some complex number and this case could be considered as "unphysical".

I don't think that's necessary at this stage.  The point is the job tests what it's supposed to.  But thanks for the offer.

**Comment by kakirastern** [comment]
I am seeing a different set of failures in the output of the `ci/circleci: 32bit` test this time around. In a sense this is a good sign. Will work on resolving these (except for the `irispy` module-not-found error) soon.

**Comment by DanRyanIrish** [comment]
> I am seeing a different set of failures in the output of the `ci/circleci: 32bit` test this time around. In a sense this is a good sign. Will work on resolving these (except for the `irispy` module-not-found error) soon.

Hi @kakirastern, yes don't try to fix the ```irispy not found``` issues as part of this PR.  The doctest error can be fixed by adding ```>>> import astropy.units as u``` in front of line 258 in docs/data_classes.rst.  I suspect the ```apply_exposure_time``` fails are a simple fix but needs a little digging to figure out what that is.

**Comment by kakirastern** [comment]
> Hi @kakirastern, yes don't try to fix the `irispy not found` issues as part of this PR. The doctest error can be fixed by adding `>>> import astropy.units as u` in front of line 258 in docs/data_classes.rst. I suspect the `apply_exposure_time` fails are a simple fix but needs a little digging to figure out what that is.
> 
> This PR also needs a changelog if you would like to add them. Do you know the current procedure for adding a changelog? Can't remember if it just before or after you started working on irispy.
> In case it's changed since, here are the [instructions](https://github.com/sunpy/sunpy/blob/master/changelog/README.rst). You have to make a new file in the changelog dir with a specifically formatted name.

Hi @DanRyanIrish Not a problem. I will make the changes as you have suggested. Yeah, seems like something about the `apply_exposure_time` function is causing some issue(s) involving the `ndcube` package. And sure, I could add a changelog to this PR soon. I will do all of these in one batch within a day or two.

**Comment by kakirastern** [comment]
Have added a changelog entry for this PR as well as debugged remaining issues known at this stage via https://github.com/DanRyanIrish/sunraster/pull/2.

**Comment by kakirastern** [comment]
Interesting. The errors for the `py36` environment for the `ci/circleci: 32bit` checks on GitHub look different from the ones I got for `py37` and `py38`. Let me get the `py36` interpreter installed on my local machine and see if I can reproduce these results locally. Unless we will phase out support for `py36` with the release of `sunraster` version 0.1, I think I should try to find a solution to this issue.

**Comment by DanRyanIrish** [comment]
Thanks for you PR @kakirastern.  I just pushed some work on testing that I forgot to finish and push to the PR.  Have a look and see if this solves the issues you were seeing or if it raises new concerns.

**Comment by DanRyanIrish** [comment]
@kakirastern, I see the issue you are talking about now.  I think we should retemplate this repo with the latest sunpy template.  This will update the CI setup and may resolve this issue for us.  Perhaps tomorrow you could ask @nabobalis or @Cadair to show us how to do that.

**Comment by DanRyanIrish** [comment]
Until then, perhaps you could decide whether you can approve this PR, pending the test issues.

**Comment by nabobalis** [comment]
Ignoring the 32bit build, the other two failures look legit to me.

**Comment by kakirastern** [comment]
Hi @DanRyanIrish Sure, let me look into the issue a bit more deeply and work with both @nabobalis and @Cadair to resolve them tomorrow.

**Comment by DanRyanIrish** [comment]
Thanks @nabobalis.  Perhaps we could retemplate this repo some time next week when it suits you or @Cadair to show us how.

@kakirastern, could check out just the ```twine-check``` and ```html-docs``` failures.  Once they are understood and/or addressed, I think this PR will be ready to merge.
Next week we can discuss more work that needs doing on the IRIS-specific code.  But I've yet to get some feedback from other developers about moving this to the ```sunkit-instruments``` package as suggested in [sunkit-instruments issue 5](https://github.com/sunpy/sunkit-instruments/issues/5).  Once this is cleared up, there'll be plenty to sink your teeth into!

**Comment by kakirastern** [comment]
> Thanks @nabobalis. Perhaps we could retemplate this repo some time next week when it suits you or @Cadair to show us how.
> 
> @kakirastern, could check out just the `twine-check` and `html-docs` failures. Once they are understood and/or addressed, I think this PR will be ready to merge.
> Next week we can discuss more work that needs doing on the IRIS-specific code. But I've yet to get some feedback from other developers about moving this to the `sunkit-instruments` package as suggested in [sunkit-instruments issue 5](https://github.com/sunpy/sunkit-instruments/issues/5). Once this is cleared up, there'll be plenty to sink your teeth into!

Sounds good @DanRyanIrish!

**Comment by kakirastern** [comment]
After discussion with @nabobalis and @Cadair on the Riot IRC channel, have opened a PR to pin pytest to an older version as a fix. Please see https://github.com/DanRyanIrish/sunraster/pull/3.

**Comment by kakirastern** [comment]
Great, it looks like the CI tests are finally running for the `py36` environment and are yielding some meaningful results (i.e. failures) now.

**Comment by kakirastern** [comment]
Am seeing the following error while trying to pass all the ci/circleci locally: `html-docs` checks:
```
Warning, treated as error:
/Users/krisstern/sunraster/.tox/build_docs/lib/python3.7/site-packages/ndcube/mixins/sequence_plotting.py:docstring of sunraster.RasterSequence.plot_as_SnS:8:Block quote ends without a blank line; unexpected unindent.
ERROR: InvocationError for command /Users/krisstern/sunraster/.tox/build_docs/bin/sphinx-build . ./_build/html -W -b html -d .docs/_build/.doctrees (exited with code 2)
_______________________________________________________________________________________ summary _______________________________________________________________________________________
ERROR:   build_docs: commands failed
```
This means that I will need to submit a PR to `ndcube` to patch a docstring in https://github.com/sunpy/ndcube/blob/master/ndcube/mixins/sequence_plotting.py#L139, in order to fix the "[block] quote ends without a blank line" and "unexpected unindent" issues. Will follow up on the `ndcube` repository soon.

**Comment by DanRyanIrish** [comment]
OK.  Sounds good @kakirastern.  Although this is only a "Warning, treated as an error".  So it doesn't mean that merging this PR is dependent on that fix in ndcube which is good news.

**Comment by kakirastern** [comment]
Awesome @DanRyanIrish The PR is here: https://github.com/sunpy/ndcube/pull/262.

**Comment by DanRyanIrish** [comment]
Hi @kakirastern.  I believe this PR is ready for merging.  Although a couple non-IRIS-specific tests are failing, the cause comes under the perview of other documented issues and will be resolved in later PRs that address those issues.  Would you be willing to approve the PR?

**Comment by kakirastern** [comment]
@DanRyanIrish Looks like it's about time to merge this PR... We can work on any outstanding issues later in some other PR's.

**Comment by DanRyanIrish** [comment]
Thanks @kakirastern! :)

**Comment by kakirastern** [comment]
You are welcome @DanRyanIrish!

**Pull request merged**
