### PR TITLE
Fixed arguments in SpectrogramCube to match NDCube

### PR DESCRIPTION
**Pull request by tiagopereira**
### Description

Fixes the interface of `SpectrogramCube` so that it works with recent versions of `ndcube`.

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
Thanks so much for this PRn @tiagopereira.  Will review now.

**Review by DanRyanIrish — CHANGES_REQUESTED** [review]
A similar change is also needed here: https://github.com/sunpy/sunraster/pull/179/files#diff-700a3462d608adc85ab8a5e9cdec91e374215a187101945d745d0f98ad207964L169

**Comment by nabobalis** [comment]
I would suggest we need a unit test of some sort to make sure this doesn't happen again.

**Comment by DanRyanIrish** [comment]
Agreed.  I'm looking into that.  @tiagopereira, could you also go through the `SpectrogramCube`s created at the top of the [test file](https://github.com/sunpy/sunraster/blob/master/sunraster/tests/test_spectrogram.py) and make they are all instantiated with kwargs?  Then could you also add a mask to [spectrogram_instrument_axes](https://github.com/sunpy/sunraster/blob/master/sunraster/tests/test_spectrogram.py#L88).  I think that should catch it.

**Review by tiagopereira — COMMENTED** [review]
Done

**Comment by DanRyanIrish** [comment]
Great!  Just realised this isn't quite enough to catch this error if it happens again.  We have a test for confirming the `instrument_axes` are [sliced properly](https://github.com/sunpy/sunraster/blob/master/sunraster/tests/test_spectrogram.py#L164), but not one to check the other attributes are.  Can you add one more test that slices `spectrogram_instrument_axes` and then calls [this ndcube function](https://github.com/sunpy/ndcube/blob/master/ndcube/tests/helpers.py#L91) that checks all the attributes are as expected?  It will require instantiating the expected cube.  But it shouldn't take much time to do.

Also, can you replace [this print statement](https://github.com/sunpy/sunraster/blob/master/sunraster/tests/test_spectrogram.py#L167)?

**Comment by tiagopereira** [comment]
I won't have time to work more on this for at least three weeks, but feel free to add the changes yourself if you want.

**Comment by DanRyanIrish** [comment]
@tiagopereira, I opened a PR to your branch that (I hope) fixes the outstanding issues on this PR.  I realise you don't have much time at the moment, but if you could quickly merge it on your end then hopefully I will be able to merge this PR and we can move ahead with another sunraster release.  Alternatively, I can close this PR and open another so I have merge rights.  Let me know which you prefer.

**Review by DanRyanIrish — APPROVED** [review]

**Comment by DanRyanIrish** [comment]
Merged!  Thanks so much @tiagopereira for this PR.  I plan to release sunraster 0.2 in the coming weeks so this bugfix will be available.

**Pull request merged**
